package com.thunisoft.znbq.bbq.smd.generator;

import com.thunisoft.znbq.bbq.smd.diff.Column;
import com.thunisoft.znbq.bbq.smd.diff.Index;
import com.thunisoft.znbq.bbq.smd.diff.Table;

/**
 *
 * @author <a href="mailto:wuzhao-1@thunisoft.com>Zhao.Wu</a>
 * @description com.thunisoft.znbq.bbq.smd.sql Barbecue
 * @date 2020/9/28 0028 20:47
 */
public class SybaseSqlGenerator implements SqlGenerator {
    public static final SqlGenerator INSTANCE = new SybaseSqlGenerator();

    @Override
    public String charset() {
        return "GBK";
    }

    @Override
    public String create(Table table) {
        StringBuilder builder = new StringBuilder();
        builder.append("-- Generated by barbecue\n\n");
        builder.append("use ").append(table.getCatalog()).append("\n");
        builder.append("go").append("\n");

        builder.append("if not exists( select 1 from sysobjects where type='U' and name= '")
                .append(table.getTableName()).append("')\n");
        builder.append("create table ").append(table.getCatalog()).append(".dbo.").append(table.getTableName()).append(" (\n");
        String primaryKey = null;
        for (Column column : table.getColumns()) {
            if (column.isPrimaryKey()) {
                primaryKey = column.getName();
            }
            columnLine(builder, column);
        }
        builder.append(')').append('\n');
        builder.append("go").append("\n");

        builder.append("if not exists( select 1 from sysindexes where name= 'CON_")
                .append(table.getTableName()).append("_").append(primaryKey).append("' and id = object_id('")
                .append(table.getTableName()).append("'))\n");
        builder.append("\talter table ").append(table.getTableName()).append(" add constraint CON_")
                .append(table.getTableName()).append("_").append(primaryKey)
                .append(" UNIQUE (").append(primaryKey).append(")\n");
        builder.append("go").append("\n");

        for (Index index : table.getIndices()) {
            builder.append(create(index));
        }

        return builder.toString();
    }

    @Override
    public String create(Column column) {
        StringBuilder builder = new StringBuilder();
        builder.append("-- Generated by barbecue\n\n");
        builder.append("use ").append(column.getTableCat()).append("\n");
        builder.append("go").append("\n");
        builder.append("IF NOT EXISTS(SELECT 1 FROM syscolumns WHERE name='").append(column.getName()).append("' ")
                .append("AND id=(SELECT id FROM sysobjects WHERE name='").append(column.getTableName())
                .append("' AND type='U'))\n");
        builder.append("    BEGIN\n");
        builder.append("        ALTER TABLE ").append(column.getTableName()).append("  ADD  ").append(column.getName()).append(" ");
        datatType(column, builder);
        if (!column.isNullable()) {
            builder.append(" NULL\n");
        } else {
            builder.append("NOT NULL\n");
        }
        builder.append("    END").append("\n");
        builder.append("go").append("\n");

        return builder.toString();
    }



    @Override
    public String create(Index index) {
        return "-- Generated by barbecue\n\n" +
                "use " + index.getTableCat() + "\n" +
                "go" + "\n" +
                "if not exists( select 1 from sysindexes where name= '" + index.getName() +
                "' and id = object_id('" + index.getTableName() + "'))\n" +
                "\tcreate " +(index.getName().contains("_PK_")?"unique ":"")+ "index " + index.getName() + " on " +
                index.getTableName() + " (" + index.fields() + ")\n" +
                "go" + "\n";
    }
}
